Update README.md
example was missing quotes around heroku -> tag causing following error when running grunt default task

```
Loading "Gruntfile.js" tasks...ERROR
>> ReferenceError: pkg is not defined
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```